### ISSUE TITLE
doi2eprintxml extra field

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/eprinttools#17]
The output of doi2eprintxml always lists the field `<corp_creators></corp_creators>`, even if the field is blank.  Records import to eprints fine whether or not this field is present.

**Comment by rsdoiel** [comment]
I think this might actually be a case of where there are corp creators but the list isn't getting generated correctly.  Reviewing problem.

**Comment by rsdoiel** [comment]
It also looks like my creators field is empty even with I should have creators.  This seems to be true using both -clsrules true and false so maybe how I am building the CorpCreatorsItemList and CreatorsItemList.

**Comment by rsdoiel** [comment]
I think this is fixed now. The problem was in the attaching the CreatorItemLists and CorpCreatorItemList as well as in how the clsrules changed those values.
