### ISSUE TITLE
ep harvest fail on Eprints deleted record 

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/eprinttools#18]
ep is failing with the following message when it encounters a non-existant record.  It should report the error but continue on with the harvest process.

Export modified 2018-09-21 00:00:00 +0000 UTC to 2018-09-28 00:00:00 +0000 UTC failed, 500 Internal Server Error for https://authors.library.caltech.edu/rest/eprint/70592/lastmod.txt

**Comment by rsdoiel** [comment]
In the loop for ListModified() there was a return rather than a cotinue with log message. Fixed it.
