### ISSUE TITLE
API endpoints behind HTTP Basic Auth

### ISSUE THREAD

**Issue by pwalsh** [caltechlibrary/eprinttools#2]
Thanks for this great library. 

I'm trying to use it to access data in an sprints repository behind auth. It is not clear if there is a way I could pass auth details when using the CLI (I have not tried to use as a go library yet).

Does this library support accessing EPrints APIs that are behind HTTP Basic Auth, and if so, how.

Thanks.

**Comment by rsdoiel** [comment]
Right now I use it to harvest public content so currently no. It will likely get that feature on the coming months as I need it to do harvests for a dark collection.  Thank you for your interest, Robert

**Comment by pwalsh** [comment]
@rsdoiel are you able to sketch out any thoughts on where/how you would deal with this in the library? And, would you consider a PR that adds this support?

**Comment by rsdoiel** [comment]
Yes, we have a similar tool for harvesting from ArchiveSpace (
http://caltechlibrary,github.io/cait) and basic auth was implemented for
that. What typically do is look for environment variabes and use those.  I
could also provide command line args though that tends to show in your
process reporting tools.

My constraint to implement this is really time as I have a couple other
things in the queue before I revisit ep.

If you need something before then you could use curl.  I believe Adam did
some YouTube examples of accessing the API before he left the EPrints
project.

All the best,

Robert

**Comment by pwalsh** [comment]
thx.

**Comment by rsdoiel** [comment]
Well, I might have BasicAuth working a little sooner than I thought.  I need to test a bunch of things which means setting up a test environment, etc. but my guess is it'll be ready  sometime in July.  Eventually I would like to support no authentication (how it works now), BasicAuth, OAuth and Shibboleth. 
All the best,

Robert

**Comment by rsdoiel** [comment]
Not sure when I implemented Basic Auth support but it seems to work for _ep_ and _eputil_ as of version v0.0.12-dev.  I need to eventually normalize the handling between both remaining utilities.
