### ISSUE TITLE
eputil auth fails with special character in password

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/eprinttools#20]
Example: eputil http://test:***@authorstest.library.caltech.edu/rest/eprint/5756.xml

Response: 401 Auth Required for http://test:***@authorstest.library.caltech.edu/rest/eprint/5756.xml

Password on sticky note
Works if password doesn't include ! mark

**Comment by rsdoiel** [comment]
Dump mistake on my part, didn't use the build-in Go package url.Parse() to pull out the username and password. Fixed in release v.0.0.35.
