### ISSUE TITLE
Add additional CrossRef fields

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/eprinttools#35]
CrossRef fields 'abstract' and 'subjects' should be mapped to the eprints fields. Example: https://api.crossref.org/works/10.1093/mnras/stab2505

**Comment by rsdoiel** [comment]
The crossrefapi package picks up the .abstract field from crossref so it must be a mapping issue inside the eprint3x.go or other re-organized file.

**Comment by rsdoiel** [comment]
Found FIXME not in crossref.go in EPrinttools. Abstract and Subjects were included in the FIXME comments.

**Comment by rsdoiel** [comment]
Fixed in release 1.1.0-rc2
