### ISSUE TITLE
Grant Numbers

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/eprinttools#36]
For works that have funders with multiple grant numbers, only the first grant number is transferred. Another listing of the funder name and the additional grant number should be added. Example https://api.crossref.org/works/10.1093/mnras/stab2505

**Comment by rsdoiel** [comment]
In EPrints GrantNumbers and Agency name are a one to one match, read in Agency name then for each grant number create an item.

**Comment by rsdoiel** [comment]
Fixed in release 1.1.0-rc2.
