### ISSUE TITLE
Add periods to given name initials

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/eprinttools#37]
When the given name contains a single characters separated by spaces, a period should be added after each initial. Example https://api.crossref.org/works/10.1093/mnras/stab2505

**Comment by rsdoiel** [comment]
Note to self, need to add this to clsrules.

**Comment by rsdoiel** [comment]
Added to clsrules ruleset and individual rule option as "dot-initials". In 1.1.0-rc2 release.
