### ISSUE TITLE
Keys should check if the record is available

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/eprinttools#6]
For example keys for CaltechTHESIS include 5230, which does not exist (https://thesis.library.caltech.edu/5230/)

**Comment by rsdoiel** [comment]
Actually this isn't possible without slowing things down.  For each key I'd have to request the actual eprint record (or part of it).  The get_keys() result is based on what eprints returns as the available list of keys. When you request individual records the 404 or 401 we get after that is a result of the state inside eprints (e.g. you're not authenticate/authorized or its record hasn't been released into the repository).  I've added an eprinttools.error_message() function that will track the last error on get_metadata() calls.

Right now I would recommend doing

```
    data = eprinttools.get_metadata(collection_name, "5230")
    e_msg = eprinttools.error_message()
    if e_msg != "":
            print(e_msg)
```

In this case the `e_msg` will reveal the you need to be authenticated to retrieve 5230. Either the record is embargoed or not public for some reason.

Thanks,

Robert
